kind: pipeline
name: default

steps:
- name: test
  image: node
  commands:
  - npm install
  - npm test
- name: export
  image: node
  commands:
  - npm install
  - npm run build
  - npm run export
deploy:
  image: drillster/drone-rsync
  hosts: [ "ruuk.io" ]
  source: ./out/*
  target: ~/ruuk.io
  recursive: true
  user: root
  delete: true
  secrets: [ rsync_key ]
  when:
    event: [ push ] ## Would run only on a push to master
    branch: [ master ] ## Only the master branch can be deployed to production
