kind: pipeline
name: default

steps:
- name: test
  image: node
  commands:
  - npm install
  - npm test
  
steps:
- name: export
  image: node
  commands:
  - npm install
  - next build
  - next export
