kind: pipeline
name: default

steps:
- name: test
  image: node
  commands:
  - npm install
  - npm run format:check
- name: export
  image: node
  commands:
  - npm install
  - npm run build
  - npm run export
- name: deploy
  image: drillster/drone-rsync
  environment:
    RSYNC_KEY:
      from_secret: rsync_key
  settings:
    hosts: 
      - ruuk.io
    port: 6113
    source: ./out/*
    target: /var/www/ruuk.io
    recursive: true
    user: root
    delete: true
    secrets: [ rsync_key ]
  when:
    branch: [ master ] ## Only the master branch can be deployed to production
