name: browserslist-update

on:
  push:
    branches:
      - "master"

jobs:
  browserslist-update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Update browserslist db
      run: npx browserslist@latest --update-db

    - uses: peter-evans/create-pull-request@v3
      with:
        title: Apply browserslist db update
        branch: actions/update-browserslist-db
        delete-branch: true
